import csv
import pandas as pd 

read = pd.read_csv('final.csv') 

del read['hyperlink']
del read['temp_planet_date']
del read['temp_planet_mass']
del read['pl_letter']
del read['pl_name']
del read['pl_discmethod']
del read['pl_controvflag']
del read['pl_pnum']
del read['pl_orbper']
del read['pl_orbpererr1']
del read['pl_orbpererr2']
del read['pl_orbperlim']
del read['pl_orbsmax']
del read['pl_orbsmaxerr1']
del read['pl_orbsmaxerr2']
del read['pl_orbsmaxlim']
del read['pl_orbeccen']
del read['pl_orbeccenerr1']
del read['pl_orbeccenerr2']
del read['pl_orbeccenlim']
del read['pl_orbincl']
del read['pl_orbinclerr1']
del read['pl_orbinclerr2']
del read['pl_orbincllim']
del read['pl_bmassj']
del read['pl_bmassjerr1']
del read['pl_bmassjerr2']
del read['pl_bmassjlim']
del read['pl_bmassprov']
del read['pl_radj']
del read['pl_radjerr1']
del read['pl_radjerr2']
del read['pl_radjlim']
del read['pl_dens']
del read['pl_denserr1']
del read['pl_denserr2']
del read['pl_denslim']
del read['pl_ttvflag']
del read["pl_kepflag"] 
del read["pl_k2flag"] 
del read["pl_nnotes"] 
del read["ra"] 
del read["dec"] 
del read["st_dist"] 
del read["st_disterr1"] 
del read["st_disterr2"] 
del read["st_distlim"] 
del read["gaia_dist"] 
del read["gaia_disterr1"] 
del read["gaia_disterr2"] 
del read["gaia_distlim"] 
del read["st_optmag"] 
del read["st_optmagerr"] 
del read["st_optmaglim"] 
del read["st_optband"] 
del read["gaia_gmag"] 
del read["gaia_gmagerr"] 
del read["gaia_gmaglim"] 
del read["st_tefferr1"] 
del read["st_tefferr2"] 
del read["st_tefflim"] 
del read["st_masserr1"] 
del read["st_masserr2"] 
del read["st_masslim"] 
del read["st_raderr1"] 
del read["st_raderr2"] 
del read["st_radlim"] 
del read["rowupdate"] 
del read["pl_facility"]

read = read.rename({'pl_hostname': 'solar_system_name', 'ra_str':'right_ascension', 'dec_str':'declination','st_teff':'host_temp','st_mass':'host_mass','st_rad':'host_radius'},axis='columns')

read.to_csv('new.csv')